# Generated by Django 3.2.7 on 2021-09-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bee',
            old_name='title',
            new_name='name',
        ),
    ]
